Add "Quiz" model
WebUI-Project-Based-10-nr/BackEnd pull request #102
Opened 2024-11-11 13:30 UTC by dimaP2341

<img width="1023" alt="Screenshot 2024-11-11 at 15 26 12" src="https://github.com/user-attachments/assets/73bd61d5-8829-4205-863c-341c679ee6ff">

2024-11-11 16:37 UTC, k7bart approved these changes

2024-11-11 18:28 UTC, Yurii-04 requested changes

2024-11-11 18:28 UTC, Yurii-04 commented on src/models/quiz.js
> +  },
`Items` must be an array of `Object Id`

2024-11-12 16:00 UTC, Yurii-04 approved these changes

2024-11-12 22:34 UTC, Annaivv approved these changes

2024-11-13 14:04 UTC, nrevutska requested changes

2024-11-13 14:04 UTC, nrevutska commented on src/test/integration/models/quiz.spec.js
> +describe.only('Quiz', () => {
remove this .only()

2024-11-14 18:31 UTC, nrevutska approved these changes

2024-11-14 18:36 UTC, merged