Add validation for subject module
WebUI-Project-Based-10-nr/BackEnd pull request #93
Opened 2024-11-06 05:23 UTC by geersann

###Issue
Open https://github.com/WebUI-Project-Based-10-nr/BackEnd/issues/3 Add validation for subject module

###Description
Added validation for subject module

###Assignees
assignees: @geersann

2024-11-06 09:45 UTC, k7bart approved these changes
The title and description are a bit confusing :)

2024-11-06 14:04 UTC, Annaivv approved these changes

2024-11-06 18:39 UTC, petro97 approved these changes

2024-11-07 11:43 UTC, k7bart requested changes
Please add a validation rule for category

2024-11-07 15:53 UTC, nrevutska approved these changes

2024-11-08 02:15 UTC, geersann commented
> Please add a validation rule for category

Already exist in models/subject.js

2024-11-08 13:00 UTC, k7bart approved these changes

2024-11-08 13:07 UTC, merged